export default {
	getStudioMetadata: '/finance/studio/metadata',
	getStudioList: '/finance/studio/list',
	getStudioCheck: '/finance/studio/list',
	getStudioNameCheck: '/finance/studio/list',
	postCreateStudio: '/finance/studio/create',
	postUpdateStudio: '/finance/studio/update',
	getFreezeList: '/finance/studio/studioFreezePaymentList',
	postStopStudio: '/finance/studio/studioOutOfService',
	postStartStudio: '/finance/studio/studioEnable',
	postTransferPayment: '/finance/studio/transferPayment',
	getAllocationList: '/finance/studio/studioAllocationList',
	getAllocationListStat: '/finance/studio/studioAllocationListStat',
	getIdCardList: '/finance/jobRecord/list',
	postIdCardListExport: '/finance/jobRecord/create',
	getStudioDetailExport: '/finance/studio/exportStudioAllocation',
}
